plugins {
    id 'com.android.application'
}

android {
    namespace 'br.org.secesd'
    compileSdk 33

    defaultConfig {
        applicationId 'br.org.secesd'
        minSdk 26
        targetSdk 33
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            // This is a sideload/test build. It is signed with Gradle's debug key; do not publish it to Play Store.
            signingConfig signingConfigs.debug
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
